version: '3.8'

services:
  app:
    build: .
    image: "go-app"
    container_name: "cars-app"
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0
    restart: unless-stopped

  db: 
    image: postgres:17-alpine
    container_name: "cars-db"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-db:
    
    